[project]
name = "pizza_and_warriors"

dependencies = [
    "pydantic-settings>=2.5.2",
    "uvicorn>=0.31.1",
    "neo4j-dao",
    "celery>=5.5.3",
    "loguru>=0.7.3",
    "redis>=5.2.1",
    "psycopg2-binary>=2.9.10",
    "sqlalchemy>=2.0.36",
    "python-parser",
]
